Repository ManageIQ/manageiq-providers-ibm_power_hmc, pull requests merged in 2021-09, with the labels that each got.

#1 Prepare initial third party services
  README.md
  lib/manageiq/providers/ibm_power_hmc/engine.rb
Labels: enhancement

#3 Fix .codeclimate for manageiq-style updates
  .codeclimate.yml
Labels: enhancement, developer

#2 Fix plugin name acronyms 2
  manageiq-providers-ibm_power_hmc.gemspec
Labels: documentation

#6 Switch to Ubuntu bionic, see: ManageIQ/manageiq#21472
  .travis.yml
Labels: test
