Repository ManageIQ/manageiq-providers-ibm_power_hmc, pull requests merged in 2022-02, with the labels that each got.

#35 Switch to GitHub Actions
  .github/workflows/ci.yaml
  .travis.yml
  README.md
  bin/before_install
  bin/ci/after_script
  bin/setup
  manageiq-providers-ibm_power_hmc.gemspec
Labels: developer, test

#36 Add Build History Graph to README.md
  README.md
Labels: developer, test

#33 Additional tests & code refactoring
  app/models/manageiq/providers/ibm_power_hmc/infra_manager/event_target_parser.rb
  app/models/manageiq/providers/ibm_power_hmc/inventory/collector/infra_manager.rb
  app/models/manageiq/providers/ibm_power_hmc/inventory/collector/target_collection.rb
  app/models/manageiq/providers/ibm_power_hmc/inventory/parser/infra_manager.rb
  manageiq-providers-ibm_power_hmc.gemspec
  spec/factories/template.rb
  spec/models/manageiq/providers/ibm_power_hmc/infra_manager/event_parser_spec.rb
  spec/models/manageiq/providers/ibm_power_hmc/infra_manager/event_target_parser_spec.rb
  spec/models/manageiq/providers/ibm_power_hmc/infra_manager/test_data/cluster.xml
  spec/models/manageiq/providers/ibm_power_hmc/infra_manager/test_data/logical_partition_long_url.xml
  spec/models/manageiq/providers/ibm_power_hmc/infra_manager/test_data/logical_partition_short_url.xml
  spec/models/manageiq/providers/ibm_power_hmc/infra_manager/test_data/managed_system.xml
  spec/models/manageiq/providers/ibm_power_hmc/infra_manager/test_data/template.xml
  spec/models/manageiq/providers/ibm_power_hmc/infra_manager/test_data/virtual_io_server_long_url.xml
  spec/models/manageiq/providers/ibm_power_hmc/infra_manager/test_data/virtual_io_server_short_url.xml
  spec/models/manageiq/providers/ibm_power_hmc/infra_manager/test_data/virtual_network_long_url.xml
  spec/models/manageiq/providers/ibm_power_hmc/infra_manager/test_data/virtual_network_short_url.xml
  spec/models/manageiq/providers/ibm_power_hmc/infra_manager/test_data/virtual_switch_long_url.xml
  spec/models/manageiq/providers/ibm_power_hmc/infra_manager/test_data/virtual_switch_short_url.xml
Labels: refactoring, test

#38 Fix vendor references
  app/models/manageiq/providers/ibm_power_hmc/inventory/parser/infra_manager.rb
  spec/models/manageiq/providers/ibm_power_hmc/infra_manager/event_target_parser_spec.rb
Labels: bug

#37 Adding procs inventory
  app/models/manageiq/providers/ibm_power_hmc/inventory/parser/infra_manager.rb
  manageiq-providers-ibm_power_hmc.gemspec
Labels: enhancement

#39 Add description for LPAR inventory
  app/models/manageiq/providers/ibm_power_hmc/inventory/parser/infra_manager.rb
  manageiq-providers-ibm_power_hmc.gemspec
Labels: enhancement

#42 Cron for GitHub Actions
  .github/workflows/ci.yaml
Labels: developer, test
