Repository ManageIQ/manageiq-providers-ibm_power_hmc, pull requests merged in 2022-07, with the labels that each got.

#67 Add CODEOWNERS for automatic review requests
  .github/CODEOWNERS
Labels: developer

#69 Removing Memoization
  app/models/manageiq/providers/ibm_power_hmc/infra_manager.rb
Labels: bug, najdorf/yes?

#68 Template Clone
  app/models/manageiq/providers/ibm_power_hmc/infra_manager/lpar.rb
  app/models/manageiq/providers/ibm_power_hmc/infra_manager/provision.rb
  app/models/manageiq/providers/ibm_power_hmc/infra_manager/provision/cloning.rb
  app/models/manageiq/providers/ibm_power_hmc/infra_manager/template.rb
  content/miq_dialogs/miq_provision_ibm_power_hmc_dialogs_clone_to_vm.yaml
  manageiq-providers-ibm_power_hmc.gemspec
  spec/factories/provision.rb
  spec/models/manageiq/providers/ibm_power_hmc/infra_manager/lpar_spec.rb
  spec/models/manageiq/providers/ibm_power_hmc/infra_manager/provision_spec.rb
  spec/models/manageiq/providers/ibm_power_hmc/infra_manager/template_spec.rb
  spec/models/manageiq/providers/ibm_power_hmc/infra_manager/vios_spec.rb
Labels: enhancement
