Repository ManageIQ/manageiq-providers-ibm_power_hmc, pull requests merged in 2022-09, with the labels that each got.

#76 Add setting to adjust HMC API request timeout
  app/models/manageiq/providers/ibm_power_hmc/infra_manager.rb
  config/settings.yml
  manageiq-providers-ibm_power_hmc.gemspec
Labels: bug, oparin/yes?

#79 Handle case where PCM enabled setting is not available
  app/models/manageiq/providers/ibm_power_hmc/inventory/parser/infra_manager.rb
Labels: bug

#82 improve operating system name parser
  app/models/manageiq/providers/ibm_power_hmc/inventory/parser/infra_manager.rb
  spec/models/manageiq/providers/ibm_power_hmc/infra_manager/refresher_spec.rb
Labels: enhancement

#77 Insert IP address used by RMC as a VM IP address
  app/models/manageiq/providers/ibm_power_hmc/inventory/parser/infra_manager.rb
  app/models/manageiq/providers/ibm_power_hmc/inventory/persister/infra_manager.rb
Labels: enhancement

#84 switch to SDK 0.14.0
  manageiq-providers-ibm_power_hmc.gemspec
  spec/vcr_cassettes/manageiq/providers/ibm_power_hmc/infra_manager/refresher.yml
Labels: enhancement

#86 [WIP] add native console for vms
  app/models/manageiq/providers/ibm_power_hmc/infra_manager/lpar.rb
  app/models/manageiq/providers/ibm_power_hmc/infra_manager/vios.rb
  app/models/manageiq/providers/ibm_power_hmc/infra_manager/vm.rb
Labels: wip
