Repository ManageIQ/manageiq-providers-ibm_power_hmc, pull requests merged in 2022-11, with the labels that each got.

#116 Errors in log due to some HMC Usertask events not handled properly
  app/models/manageiq/providers/ibm_power_hmc/infra_manager/event_target_parser.rb
  spec/models/manageiq/providers/ibm_power_hmc/infra_manager/event_target_parser_spec.rb
  spec/models/manageiq/providers/ibm_power_hmc/infra_manager/test_data/ignored_usertask.xml
Labels: bug

#115 Add shared memory pools as Resource Pools
  app/models/manageiq/providers/ibm_power_hmc/infra_manager.rb
  app/models/manageiq/providers/ibm_power_hmc/infra_manager/event_parser.rb
  app/models/manageiq/providers/ibm_power_hmc/infra_manager/event_target_parser.rb
  app/models/manageiq/providers/ibm_power_hmc/infra_manager/memory_resource_pool.rb
  app/models/manageiq/providers/ibm_power_hmc/infra_manager/processor_resource_pool.rb
  app/models/manageiq/providers/ibm_power_hmc/inventory/collector/infra_manager.rb
  app/models/manageiq/providers/ibm_power_hmc/inventory/parser/infra_manager.rb
  spec/models/manageiq/providers/ibm_power_hmc/infra_manager/event_parser_spec.rb
  spec/models/manageiq/providers/ibm_power_hmc/infra_manager/event_target_parser_spec.rb
  spec/models/manageiq/providers/ibm_power_hmc/infra_manager/refresher_spec.rb
  spec/models/manageiq/providers/ibm_power_hmc/infra_manager/test_data/shared_memory_pool.xml
  spec/vcr_cassettes/manageiq/providers/ibm_power_hmc/infra_manager/refresher.yml
  spec/vcr_cassettes/manageiq/providers/ibm_power_hmc/infra_manager/refresher_host_0685d4a6-2021-3044-84e3-59f44e9cc5d7.yml
  spec/vcr_cassettes/manageiq/providers/ibm_power_hmc/infra_manager/refresher_resource_pool_cpu__d47a585d-eaa8-3a54-b4dc-93346276ea37_c41d8844-1d39-3512-944d-50f58de2d42d.yml
  spec/vcr_cassettes/manageiq/providers/ibm_power_hmc/infra_manager/refresher_resource_pool_mem__d47a585d-eaa8-3a54-b4dc-93346276ea37_557f7755-a4dc-30de-816d-387f42dd8fd3.yml
Labels: enhancement

#120 Fix targeted collection for memory Resource Pools
  app/models/manageiq/providers/ibm_power_hmc/inventory/collector/target_collection.rb
  spec/models/manageiq/providers/ibm_power_hmc/infra_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/ibm_power_hmc/infra_manager/refresher.yml
  spec/vcr_cassettes/manageiq/providers/ibm_power_hmc/infra_manager/refresher_host_0685d4a6-2021-3044-84e3-59f44e9cc5d7.yml
  spec/vcr_cassettes/manageiq/providers/ibm_power_hmc/infra_manager/refresher_resource_pool_cpu__d47a585d-eaa8-3a54-b4dc-93346276ea37_c41d8844-1d39-3512-944d-50f58de2d42d.yml
  spec/vcr_cassettes/manageiq/providers/ibm_power_hmc/infra_manager/refresher_resource_pool_mem__d47a585d-eaa8-3a54-b4dc-93346276ea37_557f7755-a4dc-30de-816d-387f42dd8fd3.yml
Labels: bug

#121 Verify storage object in global & targeted refresh specs
  spec/models/manageiq/providers/ibm_power_hmc/infra_manager/refresher_spec.rb
Labels: enhancement, test

#114 hmc groups as vm labels
  app/models/manageiq/providers/ibm_power_hmc/inventory/collector/infra_manager.rb
  app/models/manageiq/providers/ibm_power_hmc/inventory/parser/infra_manager.rb
  app/models/manageiq/providers/ibm_power_hmc/inventory/persister/infra_manager.rb
  spec/models/manageiq/providers/ibm_power_hmc/infra_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/ibm_power_hmc/infra_manager/refresher.yml
  spec/vcr_cassettes/manageiq/providers/ibm_power_hmc/infra_manager/refresher_lpar_646AE0BC-CF06-4F6B-83CB-7A3ECCF903E3.yml
  spec/vcr_cassettes/manageiq/providers/ibm_power_hmc/infra_manager/refresher_vios_4165A16F-0766-40F3-B9E2-7272E1910F2E.yml
Labels: enhancement

#123 Use postgresql:13 image for ci
  .github/workflows/ci.yaml
Labels: test

#125 fix rubocop Layout/RescueEnsureAlignment errors
  app/models/manageiq/providers/ibm_power_hmc/inventory/collector/infra_manager.rb
  app/models/manageiq/providers/ibm_power_hmc/inventory/collector/target_collection.rb
Labels: technical debt

#118 add vm reconfiguration for cpu, memory and network
  app/models/manageiq/providers/ibm_power_hmc/infra_manager/lpar.rb
  app/models/manageiq/providers/ibm_power_hmc/infra_manager/vm.rb
  app/models/manageiq/providers/ibm_power_hmc/infra_manager/vm/reconfigure.rb
  app/models/manageiq/providers/ibm_power_hmc/inventory/parser/infra_manager.rb
  manageiq-providers-ibm_power_hmc.gemspec
Labels: enhancement

#126 collect fc ports and vfc client adapters
  app/models/manageiq/providers/ibm_power_hmc/inventory/collector/infra_manager.rb
  app/models/manageiq/providers/ibm_power_hmc/inventory/parser/infra_manager.rb
  manageiq-providers-ibm_power_hmc.gemspec
  spec/vcr_cassettes/manageiq/providers/ibm_power_hmc/infra_manager/refresher.yml
  spec/vcr_cassettes/manageiq/providers/ibm_power_hmc/infra_manager/refresher_lpar_646AE0BC-CF06-4F6B-83CB-7A3ECCF903E3.yml
  spec/vcr_cassettes/manageiq/providers/ibm_power_hmc/infra_manager/refresher_vios_4165A16F-0766-40F3-B9E2-7272E1910F2E.yml
Labels: enhancement
