Repository ManageIQ/manageiq-providers-ibm_power_hmc, pull requests merged in 2022-10, with the labels that each got.

#89 More collector improvements
  app/models/manageiq/providers/ibm_power_hmc/inventory/collector/infra_manager.rb
  app/models/manageiq/providers/ibm_power_hmc/inventory/collector/target_collection.rb
  app/models/manageiq/providers/ibm_power_hmc/inventory/parser/infra_manager.rb
  spec/vcr_cassettes/manageiq/providers/ibm_power_hmc/infra_manager/refresher.yml
Labels: enhancement

#94 Fix bug in targeted collection
  app/models/manageiq/providers/ibm_power_hmc/inventory/collector/target_collection.rb
Labels: bug

#96 Collect host hardware devices
  app/models/manageiq/providers/ibm_power_hmc/inventory/parser/infra_manager.rb
  app/models/manageiq/providers/ibm_power_hmc/inventory/persister/infra_manager.rb
Labels: enhancement

#95 Add targeted refresh tests
  spec/models/manageiq/providers/ibm_power_hmc/infra_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/ibm_power_hmc/infra_manager/refresher_host_0685d4a6-2021-3044-84e3-59f44e9cc5d7.yml
  spec/vcr_cassettes/manageiq/providers/ibm_power_hmc/infra_manager/refresher_lpar_646AE0BC-CF06-4F6B-83CB-7A3ECCF903E3.yml
  spec/vcr_cassettes/manageiq/providers/ibm_power_hmc/infra_manager/refresher_storage_8f2a83e9-f4c7-35e5-987e-9ac54a498dab.yml
  spec/vcr_cassettes/manageiq/providers/ibm_power_hmc/infra_manager/refresher_template_3f109ae5-8553-4545-b211-c0de284c4872.yml
  spec/vcr_cassettes/manageiq/providers/ibm_power_hmc/infra_manager/refresher_vios_4165A16F-0766-40F3-B9E2-7272E1910F2E.yml
Labels: enhancement, test

#92 Fix poll sleep interval in event catcher and make sure we can exit the poll loop
  app/models/manageiq/providers/ibm_power_hmc/infra_manager/event_catcher/stream.rb
Labels: bug

#97 fix error path when collecting storage pools
  app/models/manageiq/providers/ibm_power_hmc/inventory/collector/target_collection.rb
Labels: bug

#99 use new modify_object api to rename LPARs and VIOSes
  app/models/manageiq/providers/ibm_power_hmc/infra_manager/lpar.rb
  app/models/manageiq/providers/ibm_power_hmc/infra_manager/vm.rb
Labels: enhancement

#101 implement display_name for hosts and vms
  app/models/manageiq/providers/ibm_power_hmc/infra_manager/host.rb
  app/models/manageiq/providers/ibm_power_hmc/infra_manager/vios.rb
  app/models/manageiq/providers/ibm_power_hmc/infra_manager/vm.rb
Labels: enhancement

#102 supports set_description for VMs
  app/models/manageiq/providers/ibm_power_hmc/infra_manager/vm.rb
Labels: enhancement

#105 connect client network adapters to virtual lans
  app/models/manageiq/providers/ibm_power_hmc/inventory/parser/infra_manager.rb
  app/models/manageiq/providers/ibm_power_hmc/inventory/persister/infra_manager.rb
  spec/models/manageiq/providers/ibm_power_hmc/infra_manager/refresher_spec.rb
Labels: enhancement

#104 collect cpu_speed for hosts and vms
  app/models/manageiq/providers/ibm_power_hmc/inventory/collector/infra_manager.rb
  app/models/manageiq/providers/ibm_power_hmc/inventory/collector/target_collection.rb
  app/models/manageiq/providers/ibm_power_hmc/inventory/parser/infra_manager.rb
  manageiq-providers-ibm_power_hmc.gemspec
  spec/models/manageiq/providers/ibm_power_hmc/infra_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/ibm_power_hmc/infra_manager/refresher.yml
  spec/vcr_cassettes/manageiq/providers/ibm_power_hmc/infra_manager/refresher_host_0685d4a6-2021-3044-84e3-59f44e9cc5d7.yml
Labels: enhancement, unmergeable

#106 collect SEA and trunk adapters from VIOSes
  app/models/manageiq/providers/ibm_power_hmc/inventory/parser/infra_manager.rb
  manageiq-providers-ibm_power_hmc.gemspec
Labels: unmergeable

#100 Add HMC shared processor pools to inventory as 'resource pools'
  app/models/manageiq/providers/ibm_power_hmc/infra_manager.rb
  app/models/manageiq/providers/ibm_power_hmc/infra_manager/event_parser.rb
  app/models/manageiq/providers/ibm_power_hmc/infra_manager/event_target_parser.rb
  app/models/manageiq/providers/ibm_power_hmc/infra_manager/resource_pool.rb
  app/models/manageiq/providers/ibm_power_hmc/inventory/collector/infra_manager.rb
  app/models/manageiq/providers/ibm_power_hmc/inventory/collector/target_collection.rb
  app/models/manageiq/providers/ibm_power_hmc/inventory/parser/infra_manager.rb
  app/models/manageiq/providers/ibm_power_hmc/inventory/persister/infra_manager.rb
  spec/models/manageiq/providers/ibm_power_hmc/infra_manager/event_parser_spec.rb
  spec/models/manageiq/providers/ibm_power_hmc/infra_manager/event_target_parser_spec.rb
  spec/models/manageiq/providers/ibm_power_hmc/infra_manager/refresher_spec.rb
  spec/models/manageiq/providers/ibm_power_hmc/infra_manager/test_data/shared_processor_pool.xml
  spec/vcr_cassettes/manageiq/providers/ibm_power_hmc/infra_manager/refresher.yml
  spec/vcr_cassettes/manageiq/providers/ibm_power_hmc/infra_manager/refresher_resource_pool_d47a585d-eaa8-3a54-b4dc-93346276ea37_c41d8844-1d39-3512-944d-50f58de2d42d.yml
Labels: enhancement

#110 use hmc extended group attributes to reduce collection time
  app/models/manageiq/providers/ibm_power_hmc/inventory/collector/infra_manager.rb
  app/models/manageiq/providers/ibm_power_hmc/inventory/collector/target_collection.rb
  spec/models/manageiq/providers/ibm_power_hmc/inventory/collector/infra_manager_spec.rb
  spec/models/manageiq/providers/ibm_power_hmc/inventory/collector/target_collection_spec.rb
  spec/vcr_cassettes/manageiq/providers/ibm_power_hmc/infra_manager/refresher.yml
  spec/vcr_cassettes/manageiq/providers/ibm_power_hmc/infra_manager/refresher_host_0685d4a6-2021-3044-84e3-59f44e9cc5d7.yml
  spec/vcr_cassettes/manageiq/providers/ibm_power_hmc/infra_manager/refresher_lpar_646AE0BC-CF06-4F6B-83CB-7A3ECCF903E3.yml
  spec/vcr_cassettes/manageiq/providers/ibm_power_hmc/infra_manager/refresher_vios_4165A16F-0766-40F3-B9E2-7272E1910F2E.yml
Labels: enhancement, performance

#109 Filter out irrelevant HMC events
  app/models/manageiq/providers/ibm_power_hmc/infra_manager/event_catcher/stream.rb
  app/models/manageiq/providers/ibm_power_hmc/infra_manager/event_parser.rb
  config/settings.yml
  spec/models/manageiq/providers/ibm_power_hmc/infra_manager/event_parser_spec.rb
Labels: enhancement

#111 sanitize cassette and improve test coverage
  spec/models/manageiq/providers/ibm_power_hmc/infra_manager/refresher_spec.rb
  spec/spec_helper.rb
  spec/vcr_cassettes/manageiq/providers/ibm_power_hmc/infra_manager/refresher.yml
Labels: enhancement, test

#112 fix deprecation warning in lazy_find with options
  app/models/manageiq/providers/ibm_power_hmc/inventory/parser/infra_manager.rb
Labels: enhancement

#113 fail the full refresh on errors
  app/models/manageiq/providers/ibm_power_hmc/inventory/collector/infra_manager.rb
  app/models/manageiq/providers/ibm_power_hmc/inventory/collector/target_collection.rb
  manageiq-providers-ibm_power_hmc.gemspec
  spec/vcr_cassettes/manageiq/providers/ibm_power_hmc/infra_manager/refresher.yml
  spec/vcr_cassettes/manageiq/providers/ibm_power_hmc/infra_manager/refresher_storage_8f2a83e9-f4c7-35e5-987e-9ac54a498dab.yml
Labels: bug
