Repository ManageIQ/manageiq-providers-ibm_power_hmc, pull requests merged in 2023-10, with the labels that each got.

#147 Use new resource pool cpu_core_* columns
  app/models/manageiq/providers/ibm_power_hmc/inventory/parser/infra_manager.rb
  spec/models/manageiq/providers/ibm_power_hmc/infra_manager/refresher_spec.rb
Labels: enhancement

#148 Change default API port to 443
  app/models/manageiq/providers/ibm_power_hmc/infra_manager.rb
Labels: bug

#149 Update GitHub CODEOWNERS
  .github/CODEOWNERS
Labels: developer

#150 Drop Ruby 2.7
  .github/workflows/ci.yaml
Labels: dependencies
