Repository ManageIQ/manageiq-providers-ibm_power_hmc, pull requests merged in 2024-02, with the labels that each got.

#151 Drop require_nested and include_concern
  app/models/manageiq/providers/ibm_power_hmc/infra_manager.rb
  app/models/manageiq/providers/ibm_power_hmc/infra_manager/event_catcher.rb
  app/models/manageiq/providers/ibm_power_hmc/infra_manager/metrics_collector_worker.rb
  app/models/manageiq/providers/ibm_power_hmc/infra_manager/provision.rb
  app/models/manageiq/providers/ibm_power_hmc/infra_manager/refresh_worker.rb
  app/models/manageiq/providers/ibm_power_hmc/infra_manager/vm.rb
  app/models/manageiq/providers/ibm_power_hmc/inventory.rb
  app/models/manageiq/providers/ibm_power_hmc/inventory/collector.rb
  app/models/manageiq/providers/ibm_power_hmc/inventory/parser.rb
  app/models/manageiq/providers/ibm_power_hmc/inventory/persister.rb
Labels: technical debt, rails7

#152 Test with ruby 3.1 and 3.0
  .github/workflows/ci.yaml
Labels: test

#153 drop unsupported_reason_add
  app/models/manageiq/providers/ibm_power_hmc/infra_manager/host.rb
  app/models/manageiq/providers/ibm_power_hmc/infra_manager/lpar.rb
  app/models/manageiq/providers/ibm_power_hmc/infra_manager/template.rb
  app/models/manageiq/providers/ibm_power_hmc/infra_manager/vm.rb
Labels: refactoring

#154 [RADJABOV] Test radjabov with ruby 3.1
  .github/workflows/ci.yaml
Labels: test, ruby3.1
