Repository ManageIQ/manageiq-providers-ibm_power_hmc, pull requests merged in 2024-11, with the labels that each got.

#163 Testing with ruby 3.3
  .github/workflows/ci.yaml
Labels: ruby3.3

#164 Refresh entire provider for special LPAR UUID
  app/models/manageiq/providers/ibm_power_hmc/infra_manager/event_target_parser.rb
  spec/models/manageiq/providers/ibm_power_hmc/infra_manager/event_target_parser_spec.rb
  spec/models/manageiq/providers/ibm_power_hmc/infra_manager/test_data/logical_partition_invalid_uuid.xml
Labels: bug, radjabov/yes?

#167 Parse the event url with Regex not split
  app/models/manageiq/providers/ibm_power_hmc/infra_manager/event_target_parser.rb
  spec/models/manageiq/providers/ibm_power_hmc/infra_manager/event_target_parser_spec.rb
  spec/models/manageiq/providers/ibm_power_hmc/infra_manager/test_data/logical_partition_invalid_event_data.xml
Labels: refactoring
